In [1]:
import pandas as pd
#import darts 
from darts import TimeSeries
from darts.models import LinearRegressionModel
from darts.metrics import mape
from darts.utils.missing_values import extract_subseries, fill_missing_values

/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/fs/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__("pkg_resources").declare_namespace(__name__)  # type: ignore

In [2]:
df = pd.read_csv('../data/test_data.csv')
df['ts'] = pd.to_datetime(df['ts'])

In [3]:
df.isna().sum()

room_id                       0
ts                            0
room_side_hca_temp       354608
heater_side_hca_temp     354608
hca_units                     0
outside_temp                  0
inside_temp             1932400
building_id                   0
dtype: int64

In [4]:
df['ts'] = df['ts'].dt.tz_convert(None)

In [5]:
df.drop(columns=['building_id'], inplace=True)

In [6]:
value_cols = list(df.columns)
value_cols.remove('ts')
value_cols.remove('room_id')

In [7]:
darts_ts = TimeSeries.from_group_dataframe(df, time_col='ts', value_cols=value_cols, freq='H', group_cols=['room_id'])

/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)
/home/user/DFKI/heating-forecast/venv/lib/python3.12/site-packages/darts/timeseries.py:5248: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  resampled_time_index = resampled_time_index.asfreq(freq)

In [8]:
darts_ts[0].components

Index(['room_side_hca_temp', 'heater_side_hca_temp', 'hca_units',
       'outside_temp', 'inside_temp'],
      dtype='object', name='component')

In [9]:
df['room_id'].nunique()

43

In [10]:
extracted_ts = [extract_subseries(ts,min_gap_size=4, mode="any") for ts in darts_ts]

In [19]:
len(extracted_ts)

43

In [21]:
extracted_ts

[[<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8634.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8634.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8635.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8635.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8636.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8636.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8637.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8637.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8638.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8638.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8639.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8639.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8640.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8640.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8641.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8641.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8642.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8642.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8643.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8643.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8644.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8644.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8645.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8645.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8646.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8646.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8684.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8684.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8685.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8685.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8686.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8686.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8687.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8687.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8688.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8688.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8689.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8689.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8690.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8690.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8691.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8691.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8692.0
      hierarchy:          None
      metadata:           None,
  <TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:
      static_covariates:  static_covariates  room_id\nglobal_components   8692.0
      hierarchy:          None
      metadata:           None],
 [<TimeSeries (DataArray) (ts: 0, component: 5, sample: 1)> Size: 0B
  array([], shape=(0, 5, 1), dtype=float64)
  Coordinates:
    * ts         (ts) datetime64[ns] 0B
    * component  (component) object 40B 'room_side_hca_temp' ... 'inside_temp'
  Dimensions without coordinates: sample
  Attributes:

In [23]:
from darts.models import LinearRegressionModel

model = LinearRegressionModel(lags=24, output_chunk_length=12)

In [31]:
for ts in extracted_ts:
    try:
        model.fit(ts)
        print(f"Fitted model for time series with room_id: {ts['room_id'].values()[0]}")
    except Exception as e:
        print(f"Error fitting model for time series: {e}")

ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.
ValueError: Specified series do not share any common times for which features can be created.

Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.
Error fitting model for time series: Specified series do not share any common times for which features can be created.

In [1]:
import pandas as pd

ses = pd.read_csv('../data/ses_report.csv')

In [ ]:
#Comment out the callable code from DP, make it work with default split logic
#Train 1 single model on all rooms. 
#Data source to retunr the list of all data, which can be > the number of rooms
#The final list from baltbestaggregatedapidata will have 356 elements.

In [10]:
ses[ses['overlap_len'] > 1500]

,room_id,unit_id,building_id,heating_year,inside_temp_season,outside_temp_season,heater_side_hca_temp_season,room_side_hca_temp_season,hca_units_season,overlap_season,overlap_start_ts,overlap_end_ts,overlap_len
359,301,105,16,2021,1,1,1,1,1,1,2020-12-03 14:00:00+00:00,2021-02-04 09:00:00+00:00,1508
365,302,105,16,2020,1,1,1,1,1,1,2019-10-27 01:00:00+00:00,2020-02-02 01:00:00+00:00,2353
428,313,107,16,2020,1,1,1,1,1,1,2019-11-07 23:00:00+00:00,2020-01-31 09:00:00+00:00,2027
824,498,188,26,2020,1,1,1,1,1,1,2020-02-24 09:00:00+00:00,2020-06-24 13:00:00+00:00,2909
830,499,188,26,2019,1,1,1,1,1,1,2018-11-02 00:00:00+00:00,2019-03-06 23:00:00+00:00,3000
831,499,188,26,2020,1,1,1,1,1,1,2019-11-11 17:00:00+00:00,2020-01-25 00:00:00+00:00,1784
838,500,188,26,2020,1,1,1,1,1,1,2019-10-27 05:00:00+00:00,2020-01-10 18:00:00+00:00,1814
845,501,188,26,2020,1,1,1,1,1,1,2020-02-20 06:00:00+00:00,2020-06-25 07:00:00+00:00,3026
1041,536,194,26,2020,1,1,1,1,1,1,2020-01-28 15:00:00+00:00,2020-04-08 21:00:00+00:00,1711
1047,537,194,26,2019,1,1,1,1,1,1,2018-12-25 05:00:00+00:00,2019-03-11 08:00:00+00:00,1828
1194,625,236,39,2021,1,1,1,1,1,1,2020-10-25 01:00:00+00:00,2021-02-12 03:00:00+00:00,2643
1397,665,245,39,2021,1,1,1,1,1,1,2020-10-30 19:00:00+00:00,2021-01-29 21:00:00+00:00,2187
1648,939,357,57,2021,1,1,1,1,1,1,2020-12-03 14:00:00+00:00,2021-02-12 03:00:00+00:00,1694
1653,940,357,57,2019,1,1,1,1,1,1,2018-11-20 05:00:00+00:00,2019-02-07 00:00:00+00:00,1892
1655,940,357,57,2021,1,1,1,1,1,1,2020-12-09 09:00:00+00:00,2021-02-12 03:00:00+00:00,1555
1731,953,359,57,2021,1,1,1,1,1,1,2020-11-25 11:00:00+00:00,2021-02-05 13:00:00+00:00,1731
1752,957,360,57,2021,1,1,1,1,1,1,2020-11-23 11:00:00+00:00,2021-02-12 03:00:00+00:00,1937
1759,958,360,57,2021,1,1,1,1,1,1,2020-12-11 15:00:00+00:00,2021-02-12 03:00:00+00:00,1501
1765,959,360,57,2020,1,1,1,1,1,1,2019-12-26 23:00:00+00:00,2020-04-05 09:00:00+00:00,2411
1820,969,362,57,2019,1,1,1,1,1,1,2018-12-20 08:00:00+00:00,2019-03-01 07:00:00+00:00,1704
1843,972,362,57,2021,1,1,1,1,1,1,2020-12-08 01:00:00+00:00,2021-02-12 03:00:00+00:00,1587
1855,975,363,57,2019,1,1,1,1,1,1,2018-10-28 01:00:00+00:00,2019-03-21 08:00:00+00:00,3464
1856,975,363,57,2020,1,1,1,1,1,1,2019-10-27 01:00:00+00:00,2020-03-08 09:00:00+00:00,3201
1857,975,363,57,2021,1,1,1,1,1,1,2020-11-03 20:00:00+00:00,2021-02-12 03:00:00+00:00,2408
1864,976,363,57,2021,1,1,1,1,1,1,2020-12-11 10:00:00+00:00,2021-02-12 03:00:00+00:00,1506
2038,1006,368,57,2020,1,1,1,1,1,1,2020-01-04 16:00:00+00:00,2020-04-05 08:00:00+00:00,2201
2039,1006,368,57,2021,1,1,1,1,1,1,2020-12-03 08:00:00+00:00,2021-02-12 03:00:00+00:00,1700
2052,1008,368,57,2020,1,1,1,1,1,1,2019-12-31 18:00:00+00:00,2020-03-07 19:00:00+00:00,1610
2053,1008,368,57,2021,1,1,1,1,1,1,2020-11-03 20:00:00+00:00,2021-02-12 03:00:00+00:00,2408
4199,5896,639,52,2019,1,1,1,1,1,1,2018-10-28 01:00:00+00:00,2019-01-03 16:00:00+00:00,1624
4221,5899,639,52,2020,1,1,1,1,1,1,2020-01-25 18:00:00+00:00,2020-05-09 21:00:00+00:00,2524
4325,5914,632,52,2019,1,1,1,1,1,1,2018-11-26 07:00:00+00:00,2019-01-31 17:00:00+00:00,1595
4333,5915,632,52,2020,1,1,1,1,1,1,2019-10-27 01:00:00+00:00,2020-01-25 00:00:00+00:00,2160
4340,5916,632,52,2020,1,1,1,1,1,1,2020-01-25 18:00:00+00:00,2020-04-29 05:00:00+00:00,2268
4424,5928,635,52,2020,1,1,1,1,1,1,2020-01-25 20:00:00+00:00,2020-04-11 12:00:00+00:00,1841
4522,5942,638,52,2020,1,1,1,1,1,1,2019-11-05 03:00:00+00:00,2020-01-25 00:00:00+00:00,1942
4528,5943,638,52,2020,1,1,1,1,1,1,2020-01-25 23:00:00+00:00,2020-04-06 11:00:00+00:00,1717
4901,6863,914,47,2021,1,1,1,1,1,1,2020-11-18 14:00:00+00:00,2021-02-02 00:00:00+00:00,1811
4915,6866,914,47,2021,1,1,1,1,1,1,2020-11-20 04:00:00+00:00,2021-01-22 10:00:00+00:00,1519

In [14]:
room_9483 = ses[(ses['room_id'] == 9483) & (ses['overlap_season']>0)][['heating_year','overlap_season','overlap_start_ts', 'overlap_end_ts', 'overlap_len']]

In [15]:
room_9483

,heating_year,overlap_season,overlap_start_ts,overlap_end_ts,overlap_len
7304,2021,1,2020-12-20 12:00:00+00:00,2021-02-04 20:00:00+00:00,1113
7305,2022,1,2021-12-30 20:00:00+00:00,2022-02-04 14:00:00+00:00,859
7306,2023,1,2023-01-14 16:00:00+00:00,2023-02-04 17:00:00+00:00,506